fos_rest :
    body_listener : true
    param_fetcher_listener : true

    vista :
        view_response_listener : ' force '
        formatos :
            jsonp : true
            json : true
            xml : false
            rss : false
        mime_types :
            json : ['application / json', 'application / x-json']
            jpg : ' image / jpg '
            png : ' image / png '
        json_handler : ~
    routing_loader :
        default_format : json
        include_format : false
    format_listener :
        regras :
            - {caminho: ^ /, prioridades: [json, jsonp], fallback_format: ~, prefer_extension: true}
    exceção :
        habilitado : true