services:
    infra.serializer.service:
        class: Infrastructure\Service\SerializerService
        arguments: ['@jms_serializer']

    infra.email.service:
        class: Infrastructure\Service\EmailService