services:
    app.oportunidade.service:
        class: AppBundle\Service\OportunidadeService
        arguments: ['@oportunidade.repository']

    app.inscricao.service:
        class: AppBundle\Service\InscricaoService
        arguments: ['@app.event-dispatcher.service','@inscricao.repository']

    app.event-dispatcher.service:
        class: AppBundle\Service\EventDispatcherService
        arguments: ['@event_dispatcher']